services:
  mongodb:
    image: mongo:7.0
    container_name: dev_mongodb
    restart: always
    ports:
      - "27017:27017" # Map cổng 27017 của máy thật vào container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_data:/data/db # Giữ dữ liệu sống sót khi tắt/xóa container

volumes:
  mongo_data: